export const experiences = [
  {
    title: "Software Engineer",
    companyName: "Terafort Limited",
    jobType: "Full-Time",
    dateOfJoining: "October 2022",
    dateOfLeaving: "Present",
    achievments: [
      "I have mentored four interns to develop their skills and achieve professional growth.",
      "Developed a Doctor's Dashboard for eShaafi's Doctors to manage their online video consultations consultations, prescriptions, and stats.",
      "I spearheaded the development of our company's website using Next.js and added engaging animations with Framer Motion.",
    ],
    technologies: [
      "SSR",
      "GSAP",
      "Framer Motion",
      "React JS",
      "Next JS",
      "MongoDB",
      "Node JS",
      "AWS",
      "Materialise UI",
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    title: "Associate Software Engineer",
    companyName: "Terafort Limited",
    jobType: "Full-Time",
    dateOfJoining: "March 2022",
    dateOfLeaving: "October 2022",
    achievments: [
      "I Managed the product from idea to launch of the admin dashboard web app of telehealthcare mobile app eShaafi in three months.",
      "Reduced development effort by 30% by re-architecting the product using react component-based architecture.",
      "Maintained high-quality code indentation and file structure.",
    ],
    technologies: [
      "Redux",
      "React JS",
      "AWS",
      "Materialise UI",
      "HTML",
      "CSS",
      "JavaScript",
    ],
  },
  {
    title: "Front-end Developer",
    companyName: "TecXra Limited",
    jobType: "Internship",
    dateOfJoining: "November 2021",
    dateOfLeaving: "March 2022",
    achievments: [
      "Rebuilt the React-based front-end application in Next js, and Tailwind CSS",
      "Learned The difference between programming and Engineering",
      "Value of time",
      "Punctuality",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Tailwind",
      "HTML",
      "CSS",
      "JavaScript",
      "Media Queries",
    ],
  },
  {
    title: "Frontend Developer",
    companyName: "Horizon Web Solutions",
    jobType: "Internship",
    dateOfJoining: "May 2021",
    dateOfLeaving: "October 2021",
    achievments: [
      "Worked as part of a team consisting of 3 other Developer, and a product manager using Agile methodologies",
      "Worked on several mobile-first web applications with rich user experiences",
      "Built a woocommerce store using a customized theme to ensure cohesive branding between the customer and the main rental website",
    ],
    technologies: [
      "Wordpress",
      "Woocommerce",
      "Avada Theme builder",
      "HTML",
      "CSS",
    ],
  },
  {
    title: "Frontend Developer",
    companyName: "GramoTech",
    jobType: "Internship",
    dateOfJoining: "Feb 2021",
    dateOfLeaving: "April 2021",
    achievments: [
      "Created web interfaces for the ThemeForest.",
      "Created a multi-platform-supporting interface, working stably on all devices and all browsers.",
      "Did PSD to HTML conversions.",
    ],
    technologies: [
      "HTML",
      "CSS",
      "Bootstrap",
      "Media Queries",
      "Flexbox",
      "CSS Grid",
    ],
  },
  {
    title: "Station Assistant",
    companyName: "The Punjab Police Lahore",
    jobType: "Full-time",
    dateOfJoining: "February 2016",
    dateOfLeaving: "September 2020",
    achievments: [
      "Disciplined.",
      "Did a lot of public interaction, and learned public speaking and management skills.",
      "Managed a lot of public applications and complaints.",
      "Learn and experience valuable lessons from the public.",
    ],
    technologies: [
      "Communication",
      "People Management",
      "Public Speaking",
      "Teamworking",
    ],
  },
];
