import { useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { useContext } from "react";
import { ContextProvider, ContextConsumer } from "@/components/ContextAPI";
export default function Home(props: any) {
  // console.log(data);
  return (
    <>
      <Head>
        <title>Umer Shabir</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={""}>
        <section className={styles.intro}>
          <h2>Hey!</h2>
          <p className="primaryText">
            I&apos;m Umer, JavaScript developer at Terafort based in Pakistan. I
            work to bring life into ideas. Let&apos;s make something great.{" "}
            <span className={styles.videoBtn}>see video description</span>
          </p>
        </section>
        <section className={styles.latest}>
          <div className={styles.heading}>
            <h3>Latest Blogs</h3>
            <Link href="/blogs" className="secondaryText">
              see all{" "}
            </Link>
          </div>
          <div className={styles.posts}>
            <ul>
              {props.posts.map(
                (
                  item: {
                    slug: string;
                    frontmatter: { title: string; date: string };
                  },
                  index: number
                ) => (
                  <li key={index}>
                    <Link href={"/blogs/" + item.slug} className="primaryText">
                      {item.frontmatter.title}
                    </Link>
                    <p className="secondaryText">{item.frontmatter.date}</p>
                  </li>
                )
              )}
            </ul>
          </div>
        </section>
        <section className={styles.latest}>
          <div className={styles.heading}>
            <h3>Latest Projects</h3>
            <Link href="/projects" className="secondaryText">
              see all{" "}
            </Link>
          </div>
          <div className={styles.posts}>
            <ul>
              {props.projects.map(
                (item: { frontmatter: { title: string } }, index: number) => (
                  <li key={index}>
                    <Link href={"/"} className="primaryText">
                      {item.frontmatter.title}
                    </Link>
                  </li>
                )
              )}
            </ul>
          </div>
        </section>
      </main>
    </>
  );
}
export async function getStaticProps() {
  const postFiles = fs.readdirSync(path.join("src", "posts"));
  const projectFiles = fs.readdirSync(path.join("src", "projects"));
  const posts = postFiles.map((filename) => {
    const slug = filename.replace(".md", "");
    const markdownWithMeta = fs.readFileSync(
      path.join("src", "posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);
    return {
      slug,
      frontmatter,
    };
  });
  const projects = projectFiles.map((filename) => {
    const slug = filename.replace(".md", "");
    const markdownWithMeta = fs.readFileSync(
      path.join("src", "projects", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);
    return {
      slug,
      frontmatter,
    };
  });
  return {
    props: {
      posts: posts,
      projects: projects,
    },
  };
}
