import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Experiences from "@/views/Experiences";
import introVideo from "../intro.mp4";

export default function Home(props: any) {
  console.log(introVideo);
  return (
    <>
      <Head>
        <title>Umer Shabir</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/author.png" />
      </Head>
      <main className={""}>
        <section className={styles.intro}>
          <h1>UMER SHABIR</h1>
          <p style={{ marginBottom: 0 }}>Full stack developer</p>
          <p style={{ marginTop: 0 }}>Python, Node, React</p>
          {/* <video autoPlay loop controls>
            <source src={introVideo} type="video/mp4" />
            Your browser does not support the video tag.
          </video> */}
        </section>
        <Experiences />
      </main>
    </>
  );
}
// getting static props
export async function getStaticProps() {
  const postFiles = fs.readdirSync(path.join("src", "posts"));
  const posts = postFiles.map((filename) => {
    const slug = filename.replace(".md", "");
    const markdownWithMeta = fs.readFileSync(
      path.join("src", "posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);
    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts: posts,
    },
  };
}
